name: Provisioning Test
on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ubuntu
    steps:
      - uses: actions/checkout@v3
      - name: setup mitamae
        run: ./bin/setup
      - name: mitamae local
        run: make mitamae-dry > output.txt
      - name: make pr comment body
        id: pr-comment-body
        if: ${{ github.event.pull_request.merged }} == false
        run: |
          text="
            ## Provisioning DryRun Output
            <details><summary>Ubuntu</summary>

              ```sh
              ${cat output.txt}
              ```
            </details>
          "
          echo "::set-output name=message_body::$text"
