name: Provisioning Test
on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ubuntu
    steps:
      - uses: actions/checkout@v3
      - name: setup mitamae
        run: ./bin/setup
      - name: mitamae local
        run: make mitamae-dry > out.txt
      - name: find pr
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open
      - name: Update Pull Request
        uses: actions/github-script@0.9.0
        if: github.ref != 'refs/heads/master'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
          GITHUB_ISSUE_NUMBER: ${{ steps.findPr.outputs.pr }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Output mitamae dry-run\`
            #### `#### Ubuntu\`
            <details><summary>Log</summary>
            \`\`\`\n
            ${cat out.txt}
            \`\`\`
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.issues.createComment({
              issue_number: process.env.GITHUB_ISSUE_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
